iter14
GevorkovG/go-shortener-tlp pull request #19
Opened 2024-12-15 14:30 UTC by GevorkovG

2024-12-28 06:48 UTC, s-shpak requested changes

2024-12-28 06:48 UTC, s-shpak commented on internal/app/shortener_test.go
> +		log.Println("Didn't create cookie string")
В тестах для логирования лучше использовать https://pkg.go.dev/testing#T.Log

2024-12-28 06:48 UTC, s-shpak commented on internal/app/urls.go
> +		log.Println("here1")
Убери логгирование для дебаггинга

2025-01-20 04:14 UTC, GevorkovG commented
Не понимаю, куда дальше копать..

2025-06-15 15:16 UTC, merged